Feature/list projects - display a status of searched projects and the latest release
brentm5/hubot-octopus-deploy pull request #3
Opened 2016-10-17 23:54 UTC by jonyeezs

This changes the helper file name from index.
Imo, index.js should define entry points (export) for modules not helpers.

Started a test suite.

Haven't gone back and written test for the other codes.

This as well, obviously, resolves #2

2016-10-18 23:10 UTC, jonyeezs commented
I know you've added in should.
I was more comfortable with chai.

We can remove chai and use should. But i quite like having sinon-chai to do my mockings.

2016-10-18 23:11 UTC, jonyeezs commented
There are two json test data files. In retrospec, it's really not needed. But if you would like it, we could just keep it.

2016-10-19 15:23 UTC, brentm5 commented
I will get to this in the next couple days thanks for the contribution!

2016-11-03 00:49 UTC, jonyeezs commented
Hi @brentm5 was wondering what the status on this is?

If you like what I'm contributing, (and if you don't mind) I'd like to ask permission as a contributor on this so i can help speed up deployment process.

All up to you :)

2016-11-03 23:28 UTC, brentm5 requested changes

2016-11-03 23:28 UTC, brentm5 commented on .editorconfig
> +# http://editorconfig.org
Can you remove this.  If you thin its needed submit another PR please

2016-11-03 23:28 UTC, brentm5 commented on test/dashboard-testdata.json
> +{
I like the test data being in a file instead of in code.  However can you trim some of this out? Preferably bare minimum of whats needed

2016-11-03 23:28 UTC, brentm5 commented on test/release-testdata.json
> +        "variableset-LibraryVariableSets-102-s-10-PF6RH",
Ditto, can you trim some of these out so its a smaller file / just seems like a bunch of waste

2016-11-03 23:28 UTC, brentm5 commented on test/tasks-test.coffee
> +SinonChai = require('sinon-chai')
Awesome adding tests!

2016-11-03 23:28 UTC, brentm5 commented on package.json
> -    "should": "^8.1.1"
If you don't need should you can remove it

2016-11-03 23:28 UTC, brentm5 commented on test/tasks-test.coffee
> +SinonChai = require('sinon-chai')
Should these be differentiated (as in tasks be in their own test folder and unit tests be in their own folder?)

2016-11-03 23:28 UTC, brentm5 commented on test/status-report-test.coffee
> +jsonFile = require 'json-file-plus'
Any reason you arent just using json.parse and fs.openSync() ?  Just seems like overkill for not writing files either

2016-11-03 23:29 UTC, brentm5 commented
Can you also Update the README with your new function and what its suppose to look like when sued?

2016-11-04 04:53 UTC, jonyeezs commented on .editorconfig
> +# http://editorconfig.org
👍

2016-11-04 04:53 UTC, jonyeezs commented on test/status-report-test.coffee
> +jsonFile = require 'json-file-plus'
good idea

2016-11-04 04:54 UTC, jonyeezs commented on test/tasks-test.coffee
> +SinonChai = require('sinon-chai')
I think the file name speaks for themselves. Making it more granular on the folder structure level would just make it slightly more work to traverse.

2016-11-04 04:55 UTC, jonyeezs commented
I'll have to get to this in 3 weeks. thanks for the review!

2016-11-08 02:22 UTC, jonyeezs commented on test/dashboard-testdata.json
> +{
will do

2016-11-23 03:11 UTC, jonyeezs commented
Change the search algorithm to use index and leven. Gives better results.

Added a example on readme as well

2016-11-27 23:25 UTC, jonyeezs commented on test/dashboard-testdata.json
> +{
I've trimmed this

2016-11-30 11:04 UTC, jonyeezs commented
Hi @brentm5 I've re-squashed the commits. So looks like it has broken the git diff.
I'm going to just start a new PR. Sorry if we lost some comments here

2016-11-30 11:04 UTC, closed without merging